import { VerticalBox, Button, Slider } from "std-widgets.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 200px;
    title: "Slint Rodio Player";
    in-out property <float> progress; // 当前播放进度 (秒)
    in-out property <float> duration; // 总时长 (秒)
    in-out property <string> progress_info_str;
    callback play(path: string);
    callback pause();
    callback change_progress(sec: float);
    VerticalBox {
        Button {
            text: "Play";
            clicked => {
                root.play("audios/路过世界的旅行家.mp3");
            }
        }

        Button {
            text: "Pause/Resume";
            clicked => {
                root.pause();
            }
        }

        Slider {
            minimum: 0;
            maximum: root.duration;
            //未知原因：单向绑定无法刷新UI, 只能双向绑定
            value <=> root.progress;
            released(v) => {
                change_progress(v);
            }
        }

        Text {
            text: root.progress_info_str;
            horizontal-alignment: right;
        }
    }
}
